version: '3.1'
services:
  app:
    container_name: springapp
    build: ./
    ports:
      - "8081:8081"
    expose:
      - "8081"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/testdb
      SPRING_DATASOURCE_USERNAME: 'postgres'
      SPRING_DATASOURCE_PASSWORD: 'postgres'
    depends_on:
      - db
        
        
  db:
    image: postgres
    container_name: db
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./target/classes/db/:/docker-entrypoint-initdb.d/
    restart: always
    
volumes:
  postgres-data: